# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 05:18
from __future__ import unicode_literals

import born_user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdate', models.DateTimeField(auto_now_add=True)),
                ('updatedate', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('source', models.FileField(upload_to=born_user.models.PathAndRename('music/'))),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdate', models.DateTimeField(auto_now_add=True)),
                ('updatedate', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField()),
                ('music_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdate', models.DateTimeField(auto_now_add=True)),
                ('updatedate', models.DateTimeField(auto_now=True)),
                ('account', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('nickname', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('sex', models.CharField(blank=True, default='', max_length=2, null=True)),
                ('birthday', models.DateField(null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
