# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 11:11
from __future__ import unicode_literals

import born_user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('born_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musicfile', models.FileField(upload_to=born_user.models.PathAndRename('testmusic/'))),
            ],
        ),
    ]
